Hennessy.Web.Proto/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Hennessy.Core.Proto.Models;
using Hennessy.Web.Proto.Models.BrandViewModels;
using System.IO;
using Hennessy.Core.Proto.Models.Enum;
using Hennessy.Core.Proto.AppConfig;
using Microsoft.Extensions.Options;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Hennessy.Web.Proto.Controllers
{
    public class BrandController : BaseModelController<Brand, int>
    {
        public BrandController(ApplicationDbContext _context, IOptions<DirectoriesOptions> _directories) : base(_context, _directories)
        {
            repository = unit.Brands;
        }

        [HttpGet]
        public override IActionResult CreateOrEdit(int id, int operationId = -1)
        {
            var model = repository.GetById(id) ?? new Brand();
            var result = new CreateOrEditModel(context, model);
            ViewBag.Messages = logger.GetByOpration(operationId);
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateOrEdit(CreateOrEditModel _formResult)
        {
            if (ModelState.IsValid)
            {
                var Messages = new List<LogMessage>();
                Brand model = _formResult.model;
                unit.Images.GetAll().Where(m => (m.BrandId == model.Id) && (m.Type == ImageType.BrandGallery)).ToList().ForEach(m => { m.BrandId = null; m.Brand = null; unit.Images.Update(m);});
                unit.Commit();

                model.Images = new List<Image>();
                string upload = directories.GetPathByType(ImageType.BrandGallery);
                if (_formResult.Logo != null)
                {
                    unit.Images.GetAll().Where(m => (m.BrandId == model.Id) && (m.Type == ImageType.BrandLogo)).ToList().ForEach(m => { m.BrandId = null; m.Brand = null; unit.Images.Update(m); });
                    using (var fileStream = new FileStream(Path.Combine(upload, _formResult.Logo.FileName), FileMode.OpenOrCreate))
                    {
                        _formResult.Logo.CopyTo(fileStream);
                    }
                    Image tempImg = new Image()
                    {
                        Type = ImageType.BrandLogo,
                        Name = _formResult.Logo.FileName,
                        Brand = model
                    };
                    Messages.Add(unit.Images.Add(tempImg).Message);
                    model.Images.Add(tempImg);
                }
                else
                {
                    model.Images.Add(unit.Images.GetAll().FirstOrDefault(m => (m.BrandId == model.Id) && (m.Type == ImageType.BrandLogo)));
                }

                foreach (var item in _formResult.CurGellery)
                {
                    Image tempImg = unit.Images.GetById(item);
                    if (tempImg == null)
                    {
                        continue;
                    }
                    tempImg.Brand = model;
                    tempImg.Type = ImageType.BrandGallery;
                    Messages.Add(unit.Images.Update(tempImg).Message);
                    model.Images.Add(tempImg);
                }

                foreach (var item in _formResult.NewGallery)
                {
                    Image tempImg = new Image()
                    {
                        Name = item.FileName
                    };
                    tempImg.Type = ImageType.BrandGallery;
                    tempImg.Brand = model;
                    using (var fileStream = new FileStream(Path.Combine(upload, item.FileName), FileMode.OpenOrCreate))
                    {
                        item.CopyTo(fileStream);
                    }
                    Messages.Add(unit.Images.Add(tempImg).Message);
                    model.Images.Add(tempImg);
                }
                var result = (model.Id > 0) ? repository.Update(model) : repository.Add(model);
                Messages.Add(result.Message);
                unit.Commit();
                return RedirectToAction("CreateOrEdit", new { id = result.Object.Id, operationId = logger.Add(Messages) });
            }
            return RedirectToAction("CreateOrEdit", new { id = -1, operationId = logger.Add(GetModelStateErrors(ModelState), LogType.Error) });
        }

        [HttpPost]
        public IActionResult AddImageForm(int index)
        {
            ViewBag.Index = index;
            return View();
        }
    }
}

Hennessy.Web.Proto/Controllers/ExportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hennessy.Core.Proto.AppConfig;
using Hennessy.Core.Proto.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Hennessy.Web.Proto.Controllers
{
    public class ExportController : BaseController
    {
        public ExportController(ApplicationDbContext _context, IOptions<DirectoriesOptions> _directories) : base(_context, _directories)
        {
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Hennessy.Web.Proto/Controllers/ImportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hennessy.Core.Proto.AppConfig;
using Hennessy.Core.Proto.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Hennessy.Core.Proto.Models.Enum;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Hennessy.Web.Proto.Controllers
{
    public class ImportController : BaseController
    {
        public ImportController(ApplicationDbContext _context, IOptions<DirectoriesOptions> _directories) : base(_context, _directories)
        {
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Result()
        {
            List<Log> result = new List<Log>();
            for (int j = 0; j < 10; j++)
            {
                Log temp = new Log()
                {
                    Id = j,
#pragma warning disable CS1701 // Предполагается, что ссылка на сборку совпадает с удостоверением
                    Messages = new List<LogMessage>()
#pragma warning restore CS1701 // Предполагается, что ссылка на сборку совпадает с удостоверением
                };

                for (int i = 0; i < 5; i++)
                {
                    LogMessage tempMessage = new LogMessage()
                    {
                        Message = "Error message",
                        Type = LogType.Error,
                        Id = i
                    };
                    temp.Messages.Add(tempMessage);
                }

                for (int i = 0; i < 3; i++)
                {
                    LogMessage tempMessage = new LogMessage()
                    {
                        Message = "Warning message",
                        Type = LogType.Warning,
                        Id = i
                    };
                    temp.Messages.Add(tempMessage);
                }

                for (int i = 0; i < 8; i++)
                {
                    LogMessage tempMessage = new LogMessage()
                    {
                        Message = "Success message",
                        Type = LogType.Success,
                        Id = i
                    };
                    temp.Messages.Add(tempMessage);
                }
#pragma warning disable CS1701 // Предполагается, что ссылка на сборку совпадает с удостоверением
                result.Add(temp);
#pragma warning restore CS1701 // Предполагается, что ссылка на сборку совпадает с удостоверением
            }


            return View(result);
        }
    }
}

Hennessy.Web.Proto/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Hennessy.Core.Proto.Models;
using Hennessy.Core.Proto.AppConfig;
using Microsoft.Extensions.Options;
using Hennessy.Web.Proto.Models.RecipeViewModels;
using Hennessy.Core.Proto.Models.Enum;
using System.IO;
using Hennessy.Web.Proto.Models;

namespace Hennessy.Web.Proto.Controllers
{
    public class RecipeController : BaseModelController<Recipe, int>
    {
        public RecipeController(ApplicationDbContext _context, IOptions<DirectoriesOptions> _directories) : base(_context, _directories)
        {
            repository = unit.Recipes;
        }

        [HttpGet]
        public override IActionResult CreateOrEdit(int id, int operationId = -1)
        {

            var model = repository.GetById(id) ?? new Recipe();
            var result = new CreateOrEditModel(context, model);
            ViewBag.Messages = logger.GetByOpration(operationId);
            return View(result);
        }

        [HttpPost]
        public IActionResult CreateOrEdit(CreateOrEditModel _formResult)
        {
            if (ModelState.IsValid)
            {
                var Messages = new List<LogMessage>();
                Recipe model = _formResult.model;
                unit.Images.GetAll().Where(m => (m.RecipeId == model.Id) && (m.Type == ImageType.RecipeGallery)).ToList().ForEach(m => { m.RecipeId = null; m.Recipe = null; unit.Images.Update(m); });
                unit.Commit();

                model.Images = new List<Image>();
                string upload = directories.GetPathByType(ImageType.RecipeGallery);
                if (_formResult.Logo != null)
                {
                    unit.Images.GetAll().Where(m => (m.RecipeId == model.Id) && (m.Type == ImageType.RecipeLogo)).ToList().ForEach(m => { m.RecipeId = null; m.Recipe = null; unit.Images.Update(m); });
                    using (var fileStream = new FileStream(Path.Combine(upload, _formResult.Logo.FileName), FileMode.OpenOrCreate))
                    {
                        _formResult.Logo.CopyTo(fileStream);
                    }
                    Image tempImg = new Image()
                    {
                        Type = ImageType.RecipeLogo,
                        Name = _formResult.Logo.FileName,
                        Recipe = model
                    };
                    Messages.Add(unit.Images.Add(tempImg).Message);
                    model.Images.Add(tempImg);
                }
                else
                {
                    model.Images.Add(unit.Images.GetAll().FirstOrDefault(m => (m.RecipeId == model.Id) && (m.Type == ImageType.RecipeLogo)));
                }

                foreach (var item in _formResult.CurGellery)
                {
                    Image tempImg = unit.Images.GetById(item);
                    if (tempImg == null)
                    {
                        continue;
                    }
                    tempImg.Recipe = model;
                    tempImg.Type = ImageType.RecipeGallery;
                    Messages.Add(unit.Images.Update(tempImg).Message);
                    model.Images.Add(tempImg);
                }

                foreach (var item in _formResult.NewGallery)
                {
                    Image tempImg = new Image()
                    {
                        Name = item.FileName
                    };
                    tempImg.Type = ImageType.RecipeGallery;
                    tempImg.Recipe = model;
                    using (var fileStream = new FileStream(Path.Combine(upload, item.FileName), FileMode.OpenOrCreate))
                    {
                        item.CopyTo(fileStream);
                    }
                    Messages.Add(unit.Images.Add(tempImg).Message);
                    model.Images.Add(tempImg);
                }
                var result = (model.Id > 0) ? repository.Update(model) : repository.Add(model);
                Messages.Add(result.Message);
                unit.Commit();
                return RedirectToAction("CreateOrEdit", new { id = result.Object.Id, operationId = logger.Add(Messages) });
            }
            return RedirectToAction("CreateOrEdit", new { id = -1, operationId = logger.Add(GetModelStateErrors(ModelState), LogType.Error) });
        }
    }
}

Hennessy.Web.Proto/Views/Shared/AddImageForm.cshtml
@{
}

Hennessy.Web.Proto/Views/Shared/CreateOrEdit.cshtml
@{ 
    Type _type = Type.GetType(ViewBag.TPK);
}
@{
    Layout = "_Layout";
    ViewData["Title"] = (Model.model.Id > 0) ? $"Редактирование бренда {Model.model.Name}" : "Добавление бренда";
}


<h2>@ViewData["Title"]</h2>
<hr />
@Html.Partial("_Messages", (List<string>)ViewBag.Messages)


<form asp-action="CreateOrEdit" enctype="multipart/form-data">


        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
</form>
<hr />
<a asp-action="Index">Назад к списку</a>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        window.delayedFunction['set-form-control'] = function () {
            $('a[data-gallery]').click(function () {
                $('option[data-gallery="' + $(this).attr('data-gallery') + '"]').removeAttr('selected');
                $(this).parent().remove();
            });
        }
    </script>
}

Hennessy.Web.Proto/Views/Shared/Detail.cshtml
@model Hennessy.Core.Proto.Models.Brand
@{
    Layout = "_Layout";
    ViewData["Title"] = Model.Name;
}
<h2>@ViewData["Title"]</h2>
<hr />
<div class="row detail">
    <div class="row">
        <label class="col-xs-2">
            Название
        </label>
        <div class="col-xs-10">
            @Model.Name
        </div>
    </div>
    <div class="row">
        <label class="col-xs-2">
            Описание
        </label>
        <div class="col-xs-10">
            @Model.Description
        </div>
    </div>
    <div class="row">
        <label class="col-xs-2">
            Логотип
        </label>
        <div class="col-xs-10">
            @{ 
                var logo = Model.Images.FirstOrDefault(m => m.Type == Hennessy.Core.Proto.Models.Enum.ImageType.BrandLogo);
                if (logo != null)
                {
                    <img src="@(Url.Action("GetImage", new { id = logo.Id }))" class="img-thumbnail detail-logo" />
                }
                else
                {
                    <p class="text-danger">Изображение отсутствует</p>
                }
            }
        </div>
    </div>
    <div class="row">
        <label class="col-xs-2">
            Галерея
        </label>
        <div class="col-xs-10">
            <div class="gallery">
                @{
                    var gallery = Model.Images.Where(m => m.Type == Hennessy.Core.Proto.Models.Enum.ImageType.BrandGallery)?.ToList() ?? new List<Hennessy.Core.Proto.Models.Image>();
                    foreach (var item in gallery)
                    {
                        <div class="col-xs-3">
                            <img src="@(Url.Action("GetImage", new { id = item.Id }))" class="img-thumbnail gallery-item" />
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>
<hr />
<a asp-action="CreateOrEdit" asp-route-id="@Model.Id">Редактировать</a>
@section Scripts{
    <script>
        window.delayedFunction['resize-images'] = function ()
        {
            var tempImg = $('.gallery-item');
            getOurHeightMin(tempImg);
            console.log('work it!!');
        }
    </script>
}

Hennessy.Web.Proto/Views/Shared/Index.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Бренды";
}
<div class="row">
    <a asp-action="CreateOrEdit" class="btn btn-default">Добавить бренд</a>
</div>
<hr />

<div class="row">
    <div class="col-lg-12">
        <h2>@ViewData["Title"]</h2>
        <h2>@ViewBag.TPK</h2>
        <div class="dataTables_wrapper">
            <table class="table table-striped table-bordered table-hover" id="brand-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Название</th>
                        <th>Логотип</th>
                        <th>Количество продуктов</th>
                        <th>Статус</th>
                        <th>Дата обновления</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</div>
<hr />
<div class="row">
    <a asp-action="CreateOrEdit" class="btn btn-default">Добавить бренд</a>
</div>
@section Scripts{
    <script src="~/lib/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>
    <script>
        window.delayedFunction['set-brand-table'] = function ()
        {
            window.BrandTable = new TableObject('#brand-table');
        }
    </script>
}

Hennessy.Web.Proto/Views/Shared/_Layout.cshtml
@using System.Threading.Tasks
@using Microsoft.ApplicationInsights.Extensibility
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hennessy</title>

    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/metisMenu/dist/metisMenu.css" />
        <link rel="stylesheet" href="~/lib/morrisjs/morris.css" />
        <!-- DataTables CSS -->
        <link href="~/lib/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
        <!-- DataTables Responsive CSS -->
        <link rel="stylesheet" href="~/lib/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css" />
        <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="preloader">
        <div class="wBall" id="wBall_1">
            <div class="wInnerBall"></div>
        </div>
        <div class="wBall" id="wBall_2">
            <div class="wInnerBall"></div>
        </div>
        <div class="wBall" id="wBall_3">
            <div class="wInnerBall"></div>
        </div>
        <div class="wBall" id="wBall_4">
            <div class="wInnerBall"></div>
        </div>
        <div class="wBall" id="wBall_5">
            <div class="wInnerBall"></div>
        </div>
        <p>Пожалуйста подождите...</p>
    </div>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Hennessy || LOGO</a>
            </div>
            <div class="nav navbar-top-links navbar-right">
                @await Html.PartialAsync("_LoginPartial")
            </div>
            <div class="nav navbar-top-links navbar-collapse">
                <ul class="nav navbar-nav" id="main-panel">
                    <li>
                        <a class="top-main-menu" asp-area="" asp-controller="Home" asp-action="Index">Рабочий стол</a>
                    </li>
                    <li>
                        <a class="top-main-menu" href="#catalog" data-drop-down="true">Каталог</a>
                    </li>
                    <li>
                        <a class="top-main-menu" href="#setting" data-drop-down="true">Настройки</a>
                    </li>
                    <li>
                        <a class="top-main-menu" asp-area="" asp-controller="Home" asp-action="About">О приложении</a>
                    </li>
                    <li>
                        <a class="top-main-menu" asp-area="" asp-controller="Home" asp-action="Contact">Контакты</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav" id="catalog" style="display:none;">
                    <li>
                        <a class="top-main-menu" href="#main-panel" data-drop-down="true"> << Назад</a>
                    </li>
                    <li>
                        <a class="top-main-menu" asp-area="" asp-controller="Brand" asp-action="Index">Бренды</a>
                    </li>
                    <li>
                        <a class="top-main-menu" asp-area="" asp-controller="Product" asp-action="Index">Напитки</a>
                    </li>
                    <li>
                        <a class="top-main-menu" asp-area="" asp-controller="Recipe" asp-action="Index">Рецепты</a>
                    </li>
                    <li>
                        <a class="top-main-menu" asp-area="" asp-controller="Import" asp-action="Index">Импорт</a>
                    </li>
                    <li>
                        <a class="top-main-menu" asp-area="" asp-controller="Export" asp-action="Index">Экспорт</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav" id="setting" style="display:none;">
                    <li>
                        <a class="top-main-menu" href="#main-panel" data-drop-down="true"> << Назад</a>
                    </li>
                    <li>
                        <a class="top-main-menu" asp-area="" asp-controller="Aromatic" asp-action="Index">Ароматы</a>
                    </li>
                    <li>
                        <a class="top-main-menu" asp-area="" asp-controller="Volume" asp-action="Index">Объёмы</a>
                    </li>
                    <li>
                        <a class="top-main-menu" asp-area="" asp-controller="Home" asp-action="Logs">Логи</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-top-links -->
        </nav>
        <div id="page-wrapper">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; 2016 - MST</p>
        </footer>
    </div>
    <environment names="Development,Staging,Production">
        <!-- jQuery -->
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <!-- Metis Menu Plugin JavaScript -->
        <script src="~/lib/metisMenu/dist/metisMenu.js"></script>
        <!-- Morris Charts JavaScript -->
        <!--<script src="~/lib/raphael/raphael.js"></script>
        <script src="~/lib/morrisjs/morris.js"></script>
        <script src="~/lib/startbootstrap-sb-admin-2/dist/js/morris-data.js"></script>-->
        <!-- Custom Theme JavaScript -->
        <script src="~/lib/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script>
            window.delayedFunction['set-main-menu'] = function ()
            {
                window.MainMenu = new Object;
                $('.top-main-menu').each(function () {
                    var item = new TopMainMenuItem(this);
                    window.MainMenu[item.obj.html()] = item;
                });
            }
        </script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Hennessy.Web.Proto/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hennessy.Web.Proto</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Hennessy</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav menu-panel">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Рабочий стол</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">О приложении</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Контакты</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Hennessy.Web.Proto</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Hennessy.Web.Proto/Views/Shared/_Messages.cshtml
@model Hennessy.Core.Proto.Models.Log
@{
}

@{ 
    if (Model.Messages.Any())
    {
        <ul>
            @foreach (var item in Model.Messages)
            {
                string className = "";
                switch (item.Type)
                {
                    case Hennessy.Core.Proto.Models.Enum.LogType.Success:
                        className = "text-success";
                        break;

                    case Hennessy.Core.Proto.Models.Enum.LogType.Error:
                        className = "text-danger";
                        break;

                    case Hennessy.Core.Proto.Models.Enum.LogType.Warning:
                        className = "text-warning";
                        break;
                }
                <li><p class="@className">@item.Message</p></li>
            }
        </ul>
    }
}