Hennessy.Web.Proto/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Hennessy.Core.Proto.Models;
using Hennessy.Core.Proto.AppConfig;
using Microsoft.Extensions.Options;
using Hennessy.Web.Proto.Models.ProductViewModels;
using Hennessy.Core.Proto.Models.Enum;
using System.IO;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Hennessy.Web.Proto.Controllers
{
    public class ProductController : BaseModelController<Product, int>
    {
        public ProductController(ApplicationDbContext _context, IOptions<DirectoriesOptions> _directories) : base(_context, _directories)
        {
            repository = unit.Products;
        }

        [HttpGet]
        public override IActionResult CreateOrEdit(int id, int operationId = -1)
        {
            var model = repository.GetById(id) ?? new Product();
            var result = new CreateOrEditModel(context, model);
            ViewBag.Messages = logger.GetByOpration(operationId);
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateOrEdit(CreateOrEditModel _formResult)
        {
            if (ModelState.IsValid)
            {
                var Messages = new List<LogMessage>();
                Product model = _formResult.model;

                unit.ProductVolumes.GetAll().Where(m => (m.ProductId == model.Id))?.ToList()?.ForEach(m => unit.ProductVolumes.Remove(m));
                unit.ProductAromatics.GetAll().Where(m => (m.ProductId == model.Id))?.ToList()?.ForEach(m => unit.ProductAromatics.Remove(m));
                unit.Properties.GetAll().Where(m => m.ProductId == model.Id)?.ToList()?.ForEach(m => unit.Properties.Remove(m));
                unit.Images.GetAll().Where(m => (m.ProductId == model.Id) && (m.Type == ImageType.ProductGallery)).ToList().ForEach(m => { m.ProductId = null; m.Product = null; unit.Images.Update(m); });
                unit.ProductTags.Find(m => m.ProductId == model.Id)?.ToList().ForEach(m => unit.ProductTags.Remove(m));
                unit.ProductRecipes.Find(m => m.ProductId == model.Id)?.ToList().ForEach(m => unit.ProductRecipes.Remove(m));
                unit.Commit();

                model.Aromatics = new List<ProductAromatic>();
                model.Volumes = new List<ProductVolume>();
                model.Properties = new List<Property>();
                model.Images = new List<Image>();
                model.Tags = new List<ProductTag>();
                model.Recipes = new List<ProductRecipe>();

                foreach (var item in _formResult.Aromatics)
                {
                    ProductAromatic tempArm = new ProductAromatic()
                    {
                        AromaticId = item,
                        Product = model
                    };
                    unit.ProductAromatics.Add(tempArm);
                    model.Aromatics.Add(tempArm);
                }

                foreach (var item in _formResult.Volumes)
                {
                    ProductVolume tempVol = new ProductVolume()
                    {
                        VolumeId = item,
                        Product = model
                    };
                    unit.ProductVolumes.Add(tempVol);
                    model.Volumes.Add(tempVol);
                }

                foreach (var item in _formResult.Properties)
                {
                    Property tempProp = new Property()
                    {
                        Product = model,
                        Name = item.Name,
                        Value = item.Value,
                        Type = PropertyType.String
                    };
                    unit.Properties.Add(tempProp);
                    model.Properties.Add(tempProp);
                }

                string upload = directories.GetPathByType(ImageType.ProductGallery);
                if (_formResult.Logo != null)
                {
                    unit.Images.GetAll().Where(m => (m.ProductId == model.Id) && (m.Type == ImageType.ProductLogo)).ToList().ForEach(m => { m.ProductId = null; m.Product = null; unit.Images.Update(m); });
                    using (var fileStream = new FileStream(Path.Combine(upload, _formResult.Logo.FileName), FileMode.OpenOrCreate))
                    {
                        _formResult.Logo.CopyTo(fileStream);
                    }
                    Image tempImg = new Image()
                    {
                        Type = ImageType.ProductLogo,
                        Name = _formResult.Logo.FileName,
                        Product = model
                    };
                    Messages.Add(unit.Images.Add(tempImg).Message);
                    model.Images.Add(tempImg);
                }
                else
                {
                    model.Images.Add(unit.Images.GetAll().FirstOrDefault(m => (m.ProductId == model.Id) && (m.Type == ImageType.ProductLogo)));
                }

                foreach (var item in _formResult.CurGellery)
                {
                    Image tempImg = unit.Images.GetById(item);
                    if (tempImg == null)
                    {
                        continue;
                    }
                    tempImg.Product = model;
                    tempImg.Type = ImageType.ProductGallery;
                    Messages.Add(unit.Images.Update(tempImg).Message);
                    model.Images.Add(tempImg);
                }

                foreach (var item in _formResult.NewGallery)
                {
                    Image tempImg = new Image()
                    {
                        Name = item.FileName
                    };
                    tempImg.Type = ImageType.ProductGallery;
                    tempImg.Product = model;
                    using (var fileStream = new FileStream(Path.Combine(upload, item.FileName), FileMode.OpenOrCreate))
                    {
                        item.CopyTo(fileStream);
                    }
                    Messages.Add(unit.Images.Add(tempImg).Message);
                    model.Images.Add(tempImg);
                }

                foreach (var item in _formResult.Tags)
                {
                    var tag = unit.Tags.Find(m => m.Name.Equals(item.ToLower().Trim())).FirstOrDefault();
                    if (tag == null)
                    {
                        tag = new Tag()
                        {
                            Name = item.ToLower().Trim()
                        };
                        Messages.Add(unit.Tags.Add(tag).Message);
                    }
                    var prodTag = new ProductTag()
                    {
                        Tag = tag,
                        Product = model
                    };
                    unit.ProductTags.Add(prodTag);
                    model.Tags.Add(prodTag);
                }

                foreach (var item in _formResult.Recipes)
                {
                    ProductRecipe tempPR = new ProductRecipe()
                    {
                        Product = model,
                        RecipeId = item
                    };
                    unit.ProductRecipes.Add(tempPR);
                    model.Recipes.Add(tempPR);
                }

                var result = (model.Id > 0) ? repository.Update(model) : repository.Add(model);
                Messages.Add(result.Message);
                unit.Commit();
                return RedirectToAction("CreateOrEdit", new { id = result.Object.Id, operationId = logger.Add(Messages) });
            }
            return RedirectToAction("CreateOrEdit", new { id = -1, operationId = logger.Add(GetModelStateErrors(ModelState), LogType.Error) });
        }

        [HttpPost]
        public IActionResult GetPropertyForm(int index)
        {
            ViewBag.Index = index;
            var result = new CreateOrEditModel();
            return View(result);
        }
    }
}

Hennessy.Web.Proto/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Hennessy.Core.Proto.Models;
using Hennessy.Core.Proto.AppConfig;
using Microsoft.Extensions.Options;
using Hennessy.Web.Proto.Models.RecipeViewModels;
using Hennessy.Core.Proto.Models.Enum;
using System.IO;
using Hennessy.Web.Proto.Models;

namespace Hennessy.Web.Proto.Controllers
{
    public class RecipeController : BaseModelController<Recipe, int>
    {
        public RecipeController(ApplicationDbContext _context, IOptions<DirectoriesOptions> _directories) : base(_context, _directories)
        {
            repository = unit.Recipes;
        }

        [HttpGet]
        public override IActionResult CreateOrEdit(int id, int operationId = -1)
        {

            var model = repository.GetById(id) ?? new Recipe();
            var result = new CreateOrEditModel(context, model);
            ViewBag.Messages = logger.GetByOpration(operationId);
            return View(result);
        }

        [HttpPost]
        public IActionResult CreateOrEdit(CreateOrEditModel _formResult)
        {
            if (ModelState.IsValid)
            {
                var Messages = new List<LogMessage>();
                Recipe model = _formResult.model;
                unit.Images.GetAll().Where(m => (m.RecipeId == model.Id) && (m.Type == ImageType.RecipeGallery)).ToList().ForEach(m => { m.RecipeId = null; m.Recipe = null; unit.Images.Update(m); });
                unit.Commit();

                model.Images = new List<Image>();
                string upload = directories.GetPathByType(ImageType.RecipeGallery);
                if (_formResult.Logo != null)
                {
                    unit.Images.GetAll().Where(m => (m.RecipeId == model.Id) && (m.Type == ImageType.RecipeLogo)).ToList().ForEach(m => { m.RecipeId = null; m.Recipe = null; unit.Images.Update(m); });
                    using (var fileStream = new FileStream(Path.Combine(upload, _formResult.Logo.FileName), FileMode.OpenOrCreate))
                    {
                        _formResult.Logo.CopyTo(fileStream);
                    }
                    Image tempImg = new Image()
                    {
                        Type = ImageType.RecipeLogo,
                        Name = _formResult.Logo.FileName,
                        Recipe = model
                    };
                    Messages.Add(unit.Images.Add(tempImg).Message);
                    model.Images.Add(tempImg);
                }
                else
                {
                    model.Images.Add(unit.Images.GetAll().FirstOrDefault(m => (m.RecipeId == model.Id) && (m.Type == ImageType.RecipeLogo)));
                }

                foreach (var item in _formResult.CurGellery)
                {
                    Image tempImg = unit.Images.GetById(item);
                    if (tempImg == null)
                    {
                        continue;
                    }
                    tempImg.Recipe = model;
                    tempImg.Type = ImageType.RecipeGallery;
                    Messages.Add(unit.Images.Update(tempImg).Message);
                    model.Images.Add(tempImg);
                }

                foreach (var item in _formResult.NewGallery)
                {
                    Image tempImg = new Image()
                    {
                        Name = item.FileName
                    };
                    tempImg.Type = ImageType.RecipeGallery;
                    tempImg.Recipe = model;
                    using (var fileStream = new FileStream(Path.Combine(upload, item.FileName), FileMode.OpenOrCreate))
                    {
                        item.CopyTo(fileStream);
                    }
                    Messages.Add(unit.Images.Add(tempImg).Message);
                    model.Images.Add(tempImg);
                }
                var result = (model.Id > 0) ? repository.Update(model) : repository.Add(model);
                Messages.Add(result.Message);
                unit.Commit();
                return RedirectToAction("CreateOrEdit", new { id = result.Object.Id, operationId = logger.Add(Messages) });
            }
            return RedirectToAction("CreateOrEdit", new { id = -1, operationId = logger.Add(GetModelStateErrors(ModelState), LogType.Error) });
        }
    }
}

Hennessy.Web.Proto/Controllers/VolumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Hennessy.Core.Proto.Models;
using Hennessy.Core.Proto.AppConfig;
using Microsoft.Extensions.Options;
using Hennessy.Web.Proto.Models;
using Hennessy.Core.Proto.Models.Enum;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Hennessy.Web.Proto.Controllers
{
    public class VolumeController : BaseModelController<Volume, int>
    {
        public VolumeController(ApplicationDbContext _context, IOptions<DirectoriesOptions> _directories) : base(_context, _directories)
        {
            repository = unit.Volumes;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateOrEdit(BaseCreateOrEditModel<Volume, int> _formResult)
        {
            if (ModelState.IsValid)
            {
                var Messages = new List<LogMessage>();
                var result = (_formResult.model.Id > 0) ? repository.Update(_formResult.model) : repository.Add(_formResult.model);
                Messages.Add(result.Message);
                unit.Commit();
                return RedirectToAction("CreateOrEdit", new { id = result.Object.Id, operationId = logger.Add(Messages) });
            }
            return RedirectToAction("CreateOrEdit", new { id = -1, operationId = logger.Add(GetModelStateErrors(ModelState), LogType.Error)});
        }
    }
}

Hennessy.Web.Proto/Views/Product/Detail.cshtml
@model Hennessy.Core.Proto.Models.Product
@{
    Layout = "_Layout";
    ViewData["Title"] = Model.Name;
}
<h2>@ViewData["Title"]</h2>
<hr />
<div class="row detail">
    <div class="row">
        <label class="col-xs-2">
            Название
        </label>
        <div class="col-xs-10">
            @Model.Name
        </div>
    </div>
    <div class="row">
        <label class="col-xs-2">
            Бренд
        </label>
        <div class="col-xs-10">
            @Model.Brand.Name
        </div>
    </div>
    <div class="row">
        <label class="col-xs-2">
            Описание
        </label>
        <div class="col-xs-10">
            @Model.Description
        </div>
    </div>
    <div class="row">
        <label class="col-xs-2">
            Рецепты
        </label>
        <div class="col-xs-10">
            <ul class="list-group">
                @{ 
                    foreach (var item in Model.Recipes)
                    {
                        <li class="list-group-item">
                            <a asp-controller="Recipe" asp-action="Detail" asp-route-id="@item.RecipeId">@item.Recipe.Name</a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
    <div class="row">
        <label class="col-xs-2">
            Объёмы
        </label>
        <div class="col-xs-10">
            <ul class="list-group">
                @{
                    foreach (var item in Model.Volumes)
                    {
                        <li class="list-group-item">
                            <a asp-controller="Volume" asp-action="Detail" asp-route-id="@item.VolumeId">@item.Volume.Name</a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
    <div class="row">
        <label class="col-xs-2">
            Логотип
        </label>
        <div class="col-xs-10">
            @{ 
                var logo = Model.Images.FirstOrDefault(m => m.Type == Hennessy.Core.Proto.Models.Enum.ImageType.ProductLogo);
                if (logo != null)
                {
                    <img src="@(Url.Action("GetImage", new { id = logo.Id }))" class="img-thumbnail detail-logo" />
                }
                else
                {
                    <p class="text-danger">Изображение отсутствует</p>
                }
            }
        </div>
    </div>
    <div class="row">
        <label class="col-xs-2">
            Галерея
        </label>
        <div class="col-xs-10">
            <div class="gallery">
                @{
                    var gallery = Model.Images.Where(m => m.Type == Hennessy.Core.Proto.Models.Enum.ImageType.ProductGallery)?.ToList() ?? new List<Hennessy.Core.Proto.Models.Image>();
                    foreach (var item in gallery)
                    {
                        <div class="col-xs-3">
                            <img src="@(Url.Action("GetImage", new { id = item.Id }))" class="img-thumbnail gallery-item" />
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>
<hr />
<a asp-action="CreateOrEdit" asp-route-id="@Model.Id">Редактировать</a>
@section Scripts{
    <script>
        window.delayedFunction['resize-images'] = function ()
        {
            var tempImg = $('.gallery-item');
            getOurHeightMin(tempImg);
            console.log('work it!!');
        }
    </script>
}

Hennessy.Web.Proto/Views/Product/GetPropertyForm.cshtml
@model Hennessy.Web.Proto.Models.ProductViewModels.CreateOrEditModel
@{
    Layout = "";
    int index = ViewBag.Index;
    Layout = "";
    Model.Properties = new List<Hennessy.Core.Proto.Models.Property>();
    for (int i = 0; i < (index + 1); i++)
    {
        Model.Properties.Add(new Hennessy.Core.Proto.Models.Property());
    }
}

<li class="list-group-item col-xs-3 dinamic-item" id="property_@index">
    <span class="delete-property" data-href="property_@index">×</span>
    <input asp-for="Properties[index].Name" class="form-control" placeholder="Название свойства" />
    <hr />
    <input asp-for="Properties[index].Value" class="form-control" placeholder="Значение свойства" />
</li>

Hennessy.Web.Proto/Views/Product/Index.cshtml
@model IEnumerable<Hennessy.Core.Proto.Models.Product>
@{
    Layout = "_Layout";
    ViewData["Title"] = "Продукты";

}
<div class="row">
    <a asp-action="CreateOrEdit" class="btn btn-default">Добавить продукт</a>
</div>
<hr />
<div class="row">
    <div class="col-lg-12">
        <h2>@ViewData["Title"]</h2>
        <div class="dataTables_wrapper">
            <table class="table table-striped table-bordered table-hover" id="product-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Название</th>
                        <th>Бренд</th>
                        <th>Статус</th>
                        <th>Дата обновления</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.Brand.Name</td>
                                <td>@item.Status</td>
                                <td>@item.LastUpdate</td>
                                <td>
                                    <a asp-action="Delete" data-itemid="@item.Id" class="delete">Удалить</a> |
                                    <a asp-action="CreateOrEdit" asp-route-id="@item.Id">Редактировать</a> |
                                    <a asp-action="Detail" asp-route-id="@item.Id">Просмотреть</a>
                                </td>
                            </tr>
                        }
                        }
                </tbody>
            </table>
        </div>
    </div>
</div>
<hr />
<div class="row">
    <a asp-action="CreateOrEdit" class="btn btn-default">Добавить продукт</a>
</div>
@section Scripts{
    <script src="~/lib/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js"></script>
    <script>
        window.delayedFunction['set-product-table'] = function ()
        {
            window.ProductTable = new TableObject('#product-table');
        }
    </script>
}